#rm(list = ls())
#cat("\014")  
#library(rjson)
library(dplyr)
library(ggplot2)
library(tidyr)
library(parallel)

source("G2G.R")
source("GWAS.R")
source("summarize.R")
trace <- TRUE

####Full scenario
study_design = get_study_design(sample_size=5000, nb_strain=2, nb_pop=2)

nb_cpu = 30



########FS1
##TODO: check that AA is generated by effect size sum (this is a new function)
data = parse_G2G_config(study_design,	
	associate(
		add_AA(AA_conf(1, associated_strains = "full", associated_populations = "full", beta = 0.1)),
		add_SNP(SNP_conf(10, stratified = "full", fst_strat=0.2, bio_tag ="SNP1a"))),
	associate(
		add_AA(AA_conf(1, associated_strains = "full", associated_populations = "full", beta = 0.25)),
		add_SNP(SNP_conf(10, stratified = "full", fst_strat=0.2, bio_tag ="SNP1b"))),
	associate(
		add_AA(AA_conf(1, associated_strains = "full", associated_populations = "full", beta = 0.5)),
		add_SNP(SNP_conf(10, stratified = "full", fst_strat=0.2, bio_tag ="SNP1c"))),
	associate(
		add_AA(AA_conf(1, associated_strains = "full", associated_populations = "full", beta = 0.1)),
		add_SNP(SNP_conf(1, stratified = "full", fst_strat=0.2, bio_tag ="SNP2a")), replicate = 9),
	associate(
		add_AA(AA_conf(1, associated_strains = "full", associated_populations = "full", beta = 0.25)),
		add_SNP(SNP_conf(1, stratified = "full", fst_strat=0.2, bio_tag ="SNP2b")), replicate = 9),
	associate(
		add_AA(AA_conf(1, associated_strains = "full", associated_populations = "full", beta = 0.5)),
		add_SNP(SNP_conf(1, stratified = "full", fst_strat=0.2, bio_tag ="SNP2c")), replicate = 9),
	add_SNP(
		SNP_conf(500, stratified = "full", fst_strat=0.1),
		SNP_conf(10000)),
	add_AA(AA_conf(1000)))

data = parse_G2G_config(study_design,
	add_AA(25, fst_bias=0.02, biased = "full"),
	add_AA(25, fst_bias=0.2, biased = "full"),
	add_AA(25, fst_strat=0.02, stratified = "full"),
	add_AA(25, fst_strat=0.2, stratified = "full"),
	add_AA(25, fst_bias=0.02, fst_strat=0.2, stratified = "full", biased = "full"),
	add_AA(25, fst_bias=0.2, fst_strat=0.02, stratified = "full", biased = "full"),
	add_AA(25, fst_bias=0.02, fst_strat=0.2, stratified = "P1", biased = "A"),
	add_AA(25, fst_bias=0.2, fst_strat=0.02, stratified = "P2", biased = "A"),
	add_AA(1, associated_strains = "full", associated_populations = "full", beta = 0.1, associated_SNPs = add_SNP(10, stratified = "full", fst_strat=0.2, bio_tag ="SNP1a")),
	add_AA(1, associated_strains = "full", associated_populations = "full", beta = 0.25, associated_SNPs = add_SNP(10, stratified = "full", fst_strat=0.2, bio_tag ="SNP1b")),
	add_AA(1, associated_strains = "full", associated_populations = "full", beta = 0.5, associated_SNPs = add_SNP(10, stratified = "full", fst_strat=0.2, bio_tag ="SNP1c")),
	add_AA(1, associated_strains = "full", associated_populations = "full", beta = 0.1, associated_SNPs = add_SNP(1, stratified = "full", fst_strat=0.2, bio_tag ="SNP2a"), replicate = 9),
	add_AA(1, associated_strains = "full", associated_populations = "full", beta = 0.25, associated_SNPs = add_SNP(1, stratified = "full", fst_strat=0.2, bio_tag ="SNP2b"), replicate = 9),
	add_AA(1, associated_strains = "full", associated_populations = "full", beta = 0.5, associated_SNPs = add_SNP(1, stratified = "full", fst_strat=0.2, bio_tag ="SNP2c"), replicate = 9),
	add_SNP(500, stratified = "full", fst_strat=0.1),
	add_SNP(10000),
	add_AA(1000))

if(FALSE) {
	AA = data$AA
	SNP = data$SNP
	AA.scenarios = data$AA.scenarios
	SNP.scenarios = data$SNP.scenarios
	associations = data$associations
	rm(data)
	gc()
	res = analyse_G2G(SNP, AA, study_design, nb_cpu)
	plot_G2G(res, data.associations, data.AA.scenarios, data.SNP.scenarios)	
}
